name: Java Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run application
      run: java -cp build/classes/java/main PersonGUI
